site_name: LTRCLD-1199

theme:
  name: readthedocs   # or 'mkdocs' if you don’t want Material
  features:
    - navigation.tabs  # top-level items as tabs

nav:
  - Home: index.md
  - Lab Details: topology.md
  - Task-1: task-1.md
  - Task-2: task-2.md
  - Task-3: task-3.md
  - Cheat Sheet: swiss_knife_cheat_sheet.md  
