site_name: LTRCLD-1199 – Containers on IOS-XE
site_description: Using Containers on Cisco Edge Devices to Turbocharge Troubleshooting
site_author: Cisco Live Lab
site_url: https://joshhalley.github.io/LTRCLD-1199/
theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand

nav:
  - Home: index.md
  - Container Details: containers.md
  - Lab Tasks:
      - "Task 1 – App-Hosting Manual Deployment on IOS-XE": tasks/task-1.md
      - "Task 2 – App-Hosting Automated Deployment with Terraform": tasks/task-2.md
      - "Task 3 – Kubernetes App-Hosting using Virtual Kubelet": tasks/task-3.md
      - "Task 4 – Network Validation": tasks/task-4-basic.md
      - "Task 5 – MTR Path Analysis": tasks/task-5-mtr.md
      - "Task 6 – Web Testing & Troubleshooting": tasks/task-6-web-ts.md
      - "Task 7 – socat (SOcket CAT) Practical Use Cases": tasks/task-7-socat.md
      - "Task 8 – kcat (Kafka CAT) Connectivity & Message Flow": tasks/task-8-kcat.md
      - "Task 9 – MRTG Interface Monitoring": tasks/task-9-mrtg.md
      - "Task 10 – iPerf3 Performance Testing": tasks/task-10-iperf3.md
      - "Task 11 – Wireshark Live Packet Capture": tasks/task-11-wireshark.md
      - "Task 12 – Telegraf Monitoring with Prometheus Exporter": tasks/task-12-telegraf.md
      - "Task 13: – Deploy multiple hello-app using Virtual Kubelet": tasks/task-13-kubernetes.md
      - "Task 14: – Passwordless Access using SSH Keys": tasks/task-14-ssh-keys.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
plugins:
  - search
